/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  AutonomousAgentRegistry,
  AutonomousAgentRegistryInterface,
} from "../../contracts/AutonomousAgentRegistry";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60808060405234602657600080546001600160a01b031916331790556082908161002c8239f35b600080fdfe6080806040526004361015601257600080fd5b600090813560e01c638da5cb5b14602857600080fd5b346048578160031936011260485790546001600160a01b03168152602090f35b5080fdfea26469706673582212209357875d697d9b30da06fc201a51ee442ac6fb23367146d6449541d3880282a864736f6c63430008180033";

type AutonomousAgentRegistryConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: AutonomousAgentRegistryConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class AutonomousAgentRegistry__factory extends ContractFactory {
  constructor(...args: AutonomousAgentRegistryConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      AutonomousAgentRegistry & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): AutonomousAgentRegistry__factory {
    return super.connect(runner) as AutonomousAgentRegistry__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): AutonomousAgentRegistryInterface {
    return new Interface(_abi) as AutonomousAgentRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): AutonomousAgentRegistry {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as AutonomousAgentRegistry;
  }
}
