/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  NyigbaNames,
  NyigbaNamesInterface,
} from "../../contracts/NyigbaNames";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60808060405234602657600080546001600160a01b031916331790556082908161002c8239f35b600080fdfe6080806040526004361015601257600080fd5b600090813560e01c638da5cb5b14602857600080fd5b346048578160031936011260485790546001600160a01b03168152602090f35b5080fdfea2646970667358221220bb546a08b37290e12dde96ab391953cc07fe5df1c1f47db8f0f3a2fd84fee1ce64736f6c63430008180033";

type NyigbaNamesConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: NyigbaNamesConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class NyigbaNames__factory extends ContractFactory {
  constructor(...args: NyigbaNamesConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      NyigbaNames & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): NyigbaNames__factory {
    return super.connect(runner) as NyigbaNames__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): NyigbaNamesInterface {
    return new Interface(_abi) as NyigbaNamesInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): NyigbaNames {
    return new Contract(address, _abi, runner) as unknown as NyigbaNames;
  }
}
