/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  NyigbaGovernor,
  NyigbaGovernorInterface,
} from "../../contracts/NyigbaGovernor";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60808060405234602657600080546001600160a01b031916331790556082908161002c8239f35b600080fdfe6080806040526004361015601257600080fd5b600090813560e01c638da5cb5b14602857600080fd5b346048578160031936011260485790546001600160a01b03168152602090f35b5080fdfea26469706673582212208221a3acd8746351e49683661667b1bb02cc4190623844fc96cf6daf8c46b82664736f6c63430008180033";

type NyigbaGovernorConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: NyigbaGovernorConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class NyigbaGovernor__factory extends ContractFactory {
  constructor(...args: NyigbaGovernorConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      NyigbaGovernor & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): NyigbaGovernor__factory {
    return super.connect(runner) as NyigbaGovernor__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): NyigbaGovernorInterface {
    return new Interface(_abi) as NyigbaGovernorInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): NyigbaGovernor {
    return new Contract(address, _abi, runner) as unknown as NyigbaGovernor;
  }
}
