/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  TreasuryRewards,
  TreasuryRewardsInterface,
} from "../../contracts/TreasuryRewards";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60808060405234602657600080546001600160a01b031916331790556082908161002c8239f35b600080fdfe6080806040526004361015601257600080fd5b600090813560e01c638da5cb5b14602857600080fd5b346048578160031936011260485790546001600160a01b03168152602090f35b5080fdfea264697066735822122085fda1df045d9707986e9479961e593bc16346d076ef8f8962b15573301a1f7e64736f6c63430008180033";

type TreasuryRewardsConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: TreasuryRewardsConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class TreasuryRewards__factory extends ContractFactory {
  constructor(...args: TreasuryRewardsConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      TreasuryRewards & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): TreasuryRewards__factory {
    return super.connect(runner) as TreasuryRewards__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): TreasuryRewardsInterface {
    return new Interface(_abi) as TreasuryRewardsInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): TreasuryRewards {
    return new Contract(address, _abi, runner) as unknown as TreasuryRewards;
  }
}
